/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalframes;

import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.bean.Categoria;
import model.bean.Pedido;
import model.dao.CategoriaDAO;
import model.dao.PedidosDAO;

/**
 *
 * @author paulo
 */
public class InternalCategorias extends javax.swing.JInternalFrame {
    Categoria categoriaAtual = new Categoria();
    /**
     * Creates new form InternalCategorias
     */
    public InternalCategorias() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        readJtable();
        int idAtual = -1;
        categoriaAtual.setIdCategoria(idAtual);
        tabela.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event){
                if(!event.getValueIsAdjusting()){
                    int linhaSelecionada = tabela.getSelectedRow();
                    if(linhaSelecionada != -1) {
                        int idAtual = (int) tabela.getValueAt(linhaSelecionada, 0);
                        categoriaAtual.setIdCategoria(idAtual);
                        System.out.println(idAtual);
                    } 
                }
            }
        });
    }
    
    public void readJtable(){
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        CategoriaDAO carros = new CategoriaDAO();
        for(Categoria c : carros.read()){
            modelo.addRow (new Object[]{
                c.getIdCategoria(),
                c.getNome(),
            });
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new swing.Table();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_Categoria = new javax.swing.JLabel();
        categoria_Input = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        button_CadastrarCategoria = new swing.Button();
        button1 = new swing.Button();

        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "IdCategoria", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 460, -1));

        jPanel2.setBackground(new java.awt.Color(224, 221, 207));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("_______________");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 120, 20));

        label_Categoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_Categoria.setForeground(new java.awt.Color(83, 75, 82));
        label_Categoria.setText("Nome Categoria:");
        jPanel2.add(label_Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 69, -1, -1));

        categoria_Input.setBackground(new java.awt.Color(224, 221, 207));
        categoria_Input.setBorder(null);
        categoria_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoria_InputActionPerformed(evt);
            }
        });
        jPanel2.add(categoria_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 69, 138, -1));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 2, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(71, 68, 72));
        jLabel3.setText("Criar Categoria");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 24, 141, -1));

        button_CadastrarCategoria.setBackground(new java.awt.Color(60, 63, 65));
        button_CadastrarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        button_CadastrarCategoria.setText("Cadastrar");
        button_CadastrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CadastrarCategoriaActionPerformed(evt);
            }
        });
        jPanel2.add(button_CadastrarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 121, 89, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 320, 210));

        button1.setText("Deletar Categoria");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoria_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoria_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoria_InputActionPerformed

    private void button_CadastrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CadastrarCategoriaActionPerformed
        Categoria c = new Categoria();
        CategoriaDAO cd = new CategoriaDAO();

        String nomeCategoria = categoria_Input.getText().trim();

        // Verifica se o campo está vazio
        if(nomeCategoria.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, digite o nome da categoria.");
            return;
        }

        // Verifica se a categoria já existe no banco de dados
        if(cd.categoriaJaExiste(nomeCategoria)) {
            JOptionPane.showMessageDialog(null, "Categoria já existe.");
            return;
        }

        // Cria a categoria apenas se não existir
        c.setNome(nomeCategoria);
        cd.create(c);
        JOptionPane.showMessageDialog(null, "Categoria criada com sucesso!");
        readJtable();
    }//GEN-LAST:event_button_CadastrarCategoriaActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        CategoriaDAO dao = new CategoriaDAO();
        dao.delete(categoriaAtual);
        readJtable();
        
    }//GEN-LAST:event_button1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button button1;
    private swing.Button button_CadastrarCategoria;
    private javax.swing.JTextField categoria_Input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_Categoria;
    private swing.Table tabela;
    // End of variables declaration//GEN-END:variables
}
