/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalframes;

import javax.swing.JOptionPane;
import model.bean.Categoria;
import model.dao.CategoriaDAO;

/**
 *
 * @author Davi
 */
public class InternalCriacaoCategorias extends javax.swing.JPanel {

    /**
     * Creates new form InternalCriacaoCategorias
     */
    public InternalCriacaoCategorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_Categoria = new javax.swing.JLabel();
        categoria_Input = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        button_CadastrarCategoria = new swing.Button();

        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(224, 221, 207));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("_______________");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 120, 20));

        label_Categoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_Categoria.setForeground(new java.awt.Color(83, 75, 82));
        label_Categoria.setText("Nome Categoria:");
        jPanel1.add(label_Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 69, -1, -1));

        categoria_Input.setBackground(new java.awt.Color(224, 221, 207));
        categoria_Input.setBorder(null);
        categoria_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoria_InputActionPerformed(evt);
            }
        });
        jPanel1.add(categoria_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 69, 138, -1));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 2, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(71, 68, 72));
        jLabel3.setText("Criar Categoria");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 24, 141, -1));

        button_CadastrarCategoria.setBackground(new java.awt.Color(60, 63, 65));
        button_CadastrarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        button_CadastrarCategoria.setText("Cadastrar");
        button_CadastrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CadastrarCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(button_CadastrarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 121, 89, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 320, 210));
    }// </editor-fold>//GEN-END:initComponents

    private void categoria_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoria_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoria_InputActionPerformed

    private void button_CadastrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CadastrarCategoriaActionPerformed
    Categoria c = new Categoria();
    CategoriaDAO cd = new CategoriaDAO();
    
    String nomeCategoria = categoria_Input.getText().trim();
    
    // Verifica se o campo está vazio
    if(nomeCategoria.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, digite o nome da categoria.");
        return;
    }
    
    // Verifica se a categoria já existe no banco de dados
    if(cd.categoriaJaExiste(nomeCategoria)) {
        JOptionPane.showMessageDialog(null, "Categoria já existe.");
        return;
    }
    
    // Cria a categoria apenas se não existir
    c.setNome(nomeCategoria);
    cd.create(c);
    JOptionPane.showMessageDialog(null, "Categoria criada com sucesso!");
    }//GEN-LAST:event_button_CadastrarCategoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button button_CadastrarCategoria;
    private javax.swing.JTextField categoria_Input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_Categoria;
    // End of variables declaration//GEN-END:variables
}
