/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.JOptionPane;
import model.bean.Usuario;
import model.dao.UsuarioDAO;

/**
 *
 * @author Senai
 */
public class TelaCadastrarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form tela_login
     */
    public TelaCadastrarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Input_Email = new javax.swing.JTextField();
        Input_Senha = new javax.swing.JTextField();
        Input_Nome = new javax.swing.JTextField();
        Input_Telefone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cadastrar_Label = new javax.swing.JLabel();
        image_iagon = new javax.swing.JLabel();
        label_image = new javax.swing.JLabel();
        label_senha = new javax.swing.JLabel();
        label_nome = new javax.swing.JLabel();
        label_voltar = new javax.swing.JLabel();
        label_telefone = new javax.swing.JLabel();
        button1 = new swing.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(60, 63, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Input_Email.setBackground(new java.awt.Color(60, 63, 65));
        Input_Email.setForeground(new java.awt.Color(255, 255, 255));
        Input_Email.setBorder(null);
        jPanel1.add(Input_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 224, 200, -1));

        Input_Senha.setBackground(new java.awt.Color(60, 63, 65));
        Input_Senha.setForeground(new java.awt.Color(255, 255, 255));
        Input_Senha.setBorder(null);
        Input_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_SenhaActionPerformed(evt);
            }
        });
        jPanel1.add(Input_Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 288, 200, 20));

        Input_Nome.setBackground(new java.awt.Color(60, 63, 65));
        Input_Nome.setForeground(new java.awt.Color(255, 255, 255));
        Input_Nome.setBorder(null);
        jPanel1.add(Input_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 200, 20));

        Input_Telefone.setBackground(new java.awt.Color(60, 63, 65));
        Input_Telefone.setForeground(new java.awt.Color(255, 255, 255));
        Input_Telefone.setBorder(null);
        jPanel1.add(Input_Telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 200, 20));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("__________________________________");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("__________________________________");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("__________________________________");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("__________________________________");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        cadastrar_Label.setFont(new java.awt.Font("Sylfaen", 2, 36)); // NOI18N
        cadastrar_Label.setForeground(new java.awt.Color(255, 255, 255));
        cadastrar_Label.setText("Cadastrar");
        jPanel1.add(cadastrar_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 165, 151, -1));

        image_iagon.setForeground(new java.awt.Color(255, 255, 255));
        image_iagon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IAGON-Photoroom.png-Photoroom-removebg-preview-removebg-preview.png"))); // NOI18N
        jPanel1.add(image_iagon, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 72, -1, -1));

        label_image.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_image.setForeground(new java.awt.Color(255, 255, 255));
        label_image.setText("Email");
        jPanel1.add(label_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 219, 54, -1));

        label_senha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_senha.setForeground(new java.awt.Color(255, 255, 255));
        label_senha.setText("Senha");
        jPanel1.add(label_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 289, 54, -1));

        label_nome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_nome.setForeground(new java.awt.Color(255, 255, 255));
        label_nome.setText("Nome");
        jPanel1.add(label_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 254, 54, -1));

        label_voltar.setBackground(new java.awt.Color(20, 33, 61));
        label_voltar.setFont(new java.awt.Font("Sylfaen", 2, 24)); // NOI18N
        label_voltar.setForeground(new java.awt.Color(252, 163, 17));
        label_voltar.setText("<");
        label_voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_voltarMouseClicked(evt);
            }
        });
        jPanel1.add(label_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        label_telefone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_telefone.setForeground(new java.awt.Color(255, 255, 255));
        label_telefone.setText("Telefone");
        jPanel1.add(label_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 324, 80, -1));

        button1.setBackground(new java.awt.Color(33, 33, 33));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Cadastrar");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void label_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_voltarMouseClicked
        TelaLoginUsuario t = new TelaLoginUsuario();
        this.dispose();
        t.setVisible(true);
    }//GEN-LAST:event_label_voltarMouseClicked

    private void Input_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_SenhaActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        Usuario u = new Usuario();
        UsuarioDAO ud = new UsuarioDAO();
        int verificacao = 0;

        u.setLogin(Input_Email.getText());
        u.setNome(Input_Nome.getText());
        u.setSenha(Input_Senha.getText());
        u.setTelefone(Input_Telefone.getText());

        if (Input_Email.getText().trim().equals("") || Input_Nome.getText().trim().equals("") || Input_Senha.getText().trim().equals("") || Input_Telefone.getText().trim().equals("")) {
            verificacao = 1;
        }

        if (verificacao == 1) {
            JOptionPane.showMessageDialog(null, "preencha todos os campos por favor!");
        } else {
            JOptionPane.showMessageDialog(null, "Cadastro Realizado com Sucesso!");
            if(ud.create(u) == true){
                TelaLoginUsuario login = new TelaLoginUsuario();
                login.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Input_Email;
    private javax.swing.JTextField Input_Nome;
    private javax.swing.JTextField Input_Senha;
    private javax.swing.JTextField Input_Telefone;
    private swing.Button button1;
    private javax.swing.JLabel cadastrar_Label;
    private javax.swing.JLabel image_iagon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_image;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_senha;
    private javax.swing.JLabel label_telefone;
    private javax.swing.JLabel label_voltar;
    // End of variables declaration//GEN-END:variables
}
