/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.bean.Pedido;
import model.bean.Produto;
import model.bean.Usuario;
import model.dao.PedidosDAO;
import model.dao.ProdutosDAO;
import model.dao.UsuarioDAO;

/**
 *
 * @author Senai
 */
public class TelaPerfilUsuarios extends javax.swing.JFrame {

    Pedido usuarioAtual = new Pedido();
    Usuario u = new Usuario();
    
    ;
    /**
     * Creates new form TelaPerfilUsuarios
     */
    public TelaPerfilUsuarios() {
        initComponents();
        
        UsuarioDAO dao = new UsuarioDAO();
        u = dao.readUsuario(Usuario.getIdUsuarioAtual());
        iNome.setText("" + u.getNome());
        iEmail.setText("" + u.getLogin());
        iTelefone.setText("" + u.getTelefone());
        
        btnConfirmar.setVisible(false);

        readJtable();
        int idAtual = -1;
        usuarioAtual.setIdPedido(idAtual);
        tabela.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event){
                if(!event.getValueIsAdjusting()){
                    int linhaSelecionada = tabela.getSelectedRow();
                    if(linhaSelecionada != -1) {
                        int idAtual = (int) tabela.getValueAt(linhaSelecionada, 0);
                        usuarioAtual.setIdPedido(idAtual);
                        System.out.println(idAtual);
                    } 
                }
            }
        });
    }
    
    public void readJtable(){
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        PedidosDAO pedidosDAO = new PedidosDAO();
        for (Pedido pedido : pedidosDAO.read(Usuario.getIdUsuarioAtual())) {
        modelo.addRow(new Object[]{
            pedido.getNomeProduto(),
            pedido.getQuantidade(),
            pedido.getValorFinal(),
            pedido.getDataPedido(),
        });
    }
    }
  
    

    private String formatarData(Date data) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        return sdf.format(data);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        button1 = new swing.Button();
        jLabel3 = new javax.swing.JLabel();
        iEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        iNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        iSenha = new javax.swing.JTextField();
        btnConfirmar = new swing.Button();
        button3 = new swing.Button();
        jLabel6 = new javax.swing.JLabel();
        iTelefone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new swing.Table2();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(164, 22, 26));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (2).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Meus Pedidos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        button1.setBackground(new java.awt.Color(255, 0, 0));
        button1.setText("FECHAR");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        iEmail.setEditable(false);
        jPanel1.add(iEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 350, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        iNome.setEditable(false);
        iNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iNomeActionPerformed(evt);
            }
        });
        jPanel1.add(iNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 350, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Senha:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        iSenha.setEditable(false);
        jPanel1.add(iSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 350, -1));

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 90, -1));

        button3.setText("Alterar dados");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        jPanel1.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefone:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        iTelefone.setEditable(false);
        jPanel1.add(iTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 350, -1));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produtos", "Quantidade", "Valor", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_button1ActionPerformed
    private boolean clicado = false;
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (!clicado) {
       
        UsuarioDAO dao = new UsuarioDAO();
        u.setNome(iNome.getText());
        u.setLogin(iEmail.getText());
        u.setSenha(iSenha.getText());
        u.setTelefone(iTelefone.getText());
        dao.update(u);
        iNome.setText("" + u.getNome());
        iEmail.setText("" + u.getLogin());
        iTelefone.setText("" + u.getTelefone());
        
        iEmail.setEditable(false);
        iNome.setEditable(false);
        iSenha.setEditable(false);
        iTelefone.setEditable(false);
        btnConfirmar.setVisible(false);
        
        clicado = true;
    } else {
        
    }
        
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        iEmail.setEditable(true);
        iNome.setEditable(true);
        iSenha.setEditable(true);
        iTelefone.setEditable(true);
        btnConfirmar.setVisible(true);
    }//GEN-LAST:event_button3ActionPerformed

    private void iNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPerfilUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPerfilUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPerfilUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPerfilUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPerfilUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btnConfirmar;
    private swing.Button button1;
    private swing.Button button3;
    private javax.swing.JTextField iEmail;
    private javax.swing.JTextField iNome;
    private javax.swing.JTextField iSenha;
    private javax.swing.JTextField iTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.Table2 tabela;
    // End of variables declaration//GEN-END:variables
}
